---
- hosts: worker
  vars:
    - k3s_version: v1.23.5-rc4+k3s1
    - ansible_user: root
    - systemd_dir: /etc/systemd/system
    - master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
    - extra_agent_args: "--snapshotter=native"
    - master_token: ""
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: k3s/worker
