---

- name: Stop and disable Firewall
  systemd:
    name: firewalld
    state: stopped
    enabled: False
  
- name: Copy K3s service file
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: 0755

- name: Enable and check K3s service
  systemd:
    name: k3s.service
    daemon_reload: yes
    state: restarted
    enabled: yes
